### ISSUE TITLE
[DX11] Dragon Nest crashes when using frame limit

### ISSUE THREAD

**Issue by dnblank123** [SpecialKO/SpecialK#129] opened 2023-12-28 10:11 UTC
Let me know if there's anything I need to add.
logs: [2023-12-28__18'04'39.zip](https://github.com/SpecialKO/SpecialK/files/13785519/2023-12-28__18.04.39.zip)

**Comment by Kaldaien** [comment] 2023-12-28 22:48
> [! Except !] 	<< EXCEPTION_ILLEGAL_INSTRUCTION >>

That's almost always caused by RTSS.

**Comment by dnblank123** [comment] 2023-12-29 07:46
I uninstalled RTSS, then restarted the pc, still the same.
logs: [2023-12-29__15'42'54.zip](https://github.com/SpecialKO/SpecialK/files/13791775/2023-12-29__15.42.54.zip)

**Comment by Kaldaien** [comment] 2023-12-29 08:27
Oh, you have an AMD Ryzen CPU that doesn't support that instruction :-\

What exactly is your CPU?

**Comment by dnblank123** [comment] 2023-12-29 08:35
AMD A8-7600

**Comment by Kaldaien** [comment] 2023-12-30 19:23
Sorry for this. I had to review the processor manual, I have added extra CPUID checks before using MWAITX in 23.12.30.

Your CPU was being considered Zen by SK's CPU identification and it was skipping proper CPU capability checks, assuming all Zen features were actually available.

**Comment by dnblank123** [comment] 2023-12-31 07:54
The MWAITX is still checked at the fixed version (from the link you provided). I did a rerun with new config (deleted the old config) and its enabled.
![image](https://github.com/SpecialKO/SpecialK/assets/67945097/0c793165-5a6f-4167-b81f-5d32142fe319)

**Comment by Kaldaien** [comment] 2024-01-08 12:19
Sorry, I believe this is fixed now. I was testing the edx register instead of ecx :) There's no telling what feature I was actually testing for.

https://github.com/SpecialKO/SpecialK/actions/runs/7447277922

<hr>

As for editing shaders, this isn't currently a thing. You can edit their Constant Buffers in real-time, but I haven't written an assembler to let you modify existing shaders. 3DMigoto's much better served for that. Best I could do is let you figure out how to write an equivalent shader in HLSL and replace it with that. A lot of work that 3DMigoto's assembler saves you.

**Comment by dnblank123** [comment] 2024-01-08 12:37
Thanks for the fix, its working now, and is there any documentation/wiki I can read about editing Constant Buffers?

**Comment by Kaldaien** [comment] 2024-01-08 21:42
I never got that advanced with my tutorial series, but there's a guide on Steam.

This is the most I wrote on the subject before Valve removed Special K from Steam :(

https://steamcommunity.com/sharedfiles/filedetails/?id=1866530842


Everything was smooth sailing back when SK was projected to have a Steam release, it simplified a lot of things for me and gave me time to focus on documentation.

**Closed by Kaldaien** 2024-01-08 21:42 UTC
Labels: bug
